In [2]:
import numpy as np

data = np.load('HOPE/scene_0000_0000.npz', allow_pickle=True)

data.type :  'NpzFile' object has no attribute 'type'

In [3]:
for key in data.files:
    print(f"{key} → {type(data[key])}, shape: {getattr(data[key], 'shape', 'N/A')}")

boxes → <class 'numpy.ndarray'>, shape: (10, 4)
labels → <class 'numpy.ndarray'>, shape: (10,)
confidences → <class 'numpy.ndarray'>, shape: (10,)
features → <class 'numpy.ndarray'>, shape: (3,)
strides → <class 'numpy.ndarray'>, shape: (3,)
channels → <class 'numpy.ndarray'>, shape: (3,)
image_path → <class 'numpy.ndarray'>, shape: ()
gt_poses → <class 'numpy.ndarray'>, shape: (10, 4, 4)


In [4]:
data['boxes']

array([[0.6826747 , 0.74295783, 0.2423914 , 0.37960976],
       [0.7338554 , 0.1421779 , 0.24880485, 0.28262138],
       [0.2467914 , 0.24561076, 0.28242922, 0.48612386],
       [0.9195528 , 0.20658533, 0.16089448, 0.41317067],
       [0.18379171, 0.54761094, 0.24759999, 0.4149025 ],
       [0.5220326 , 0.07998313, 0.30971068, 0.15967448],
       [0.95314515, 0.6317328 , 0.09265633, 0.36444694],
       [0.5259021 , 0.41190663, 0.18110141, 0.33517414],
       [0.93579626, 0.12156977, 0.12752971, 0.23957399],
       [0.7552773 , 0.02211943, 0.15123215, 0.04032503]], dtype=float32)

In [5]:
data['labels']

array([ 7, 16, 13, 15, 17, 11,  0, 25,  5, 20], dtype=int32)

In [6]:
data['confidences']

array([0.9938459 , 0.97531927, 0.9656063 , 0.95086724, 0.9456813 ,
       0.9404362 , 0.93499887, 0.88978857, 0.82397056, 0.3021614 ],
      dtype=float32)

In [7]:
for i in range(data['features'].shape[0]):
    print(data['features'][i].shape)

(1, 128, 80, 80)
(1, 256, 40, 40)
(1, 512, 20, 20)


In [8]:
data['strides']

array([ 8, 16, 32], dtype=int32)

In [9]:
data['channels']

array([128, 256, 512], dtype=int32)

In [17]:
data['gt_poses'][0][:-1,:-1]

array([[0.3477880358695984, -0.9351716637611389, -0.06706294417381287],
       [0.7580374479293823, 0.23837679624557495, 0.6070879697799683],
       [-0.5517451763153076, -0.26197415590286255, 0.7917997241020203]],
      dtype=object)

In [21]:
data['gt_poses'][0][:-1,:-1]@data['gt_poses'][0][:-1,:-1].T

array([[0.9999999970770697, 2.3357991096872865e-08,
        1.5372579653671892e-08],
       [2.3357991096872865e-08, 1.000000072503159, 2.163276846545159e-08],
       [1.5372579653671892e-08, 2.163276846545159e-08,
        1.0000000010362626]], dtype=object)

In [22]:
data['gt_poses'][0][:-1,-1]

array([6.336326599121094, 6.160734176635742, 36.24346160888672],
      dtype=object)